#!/bin/bash
# Quick reference for Civ 6 BLP Extractor tool usage

echo "=== Civ 6 BLP Extractor - Quick Start ==="
echo ""
echo "1. Install dependencies:"
echo "   npm install"
echo ""
echo "2. Extract assets from a BLP file:"
echo "   npm run extract -- <file.blp> [output-dir]"
echo ""
echo "   Examples:"
echo "   npm run extract -- workdir/strategicview_terraintypes.blp"
echo "   npm run extract -- workdir/strategicview_terrainsprites.blp workdir/sprites"
echo ""
echo "3. Analyze extracted assets:"
echo "   npm run analyze -- <directory>"
echo ""
echo "   Example:"
echo "   npm run analyze -- workdir/extracted"
echo ""
echo "4. Investigate BLP file structure:"
echo "   npm run investigate -- <file.blp>"
echo ""
echo "   Example:"
echo "   npm run investigate -- workdir/strategicview_terraintypes.blp"
echo ""
echo "=== Tools Included ==="
echo ""
echo "extract-blp.ts    - Main extraction tool"
echo "investigate-blp.ts - BLP header analyzer"
echo "analyze-assets.ts - Extracted asset analyzer"
echo ""
echo "=== Output ==="
echo ""
echo "Extracted files are saved as:"
echo "  - asset_NN.raw (raw binary data)"
echo "  - asset_NN.civbig (CIVBIG containers, if detected)"
echo ""
echo "See README.md for full documentation."
